### ISSUE TITLE
./wait_for_cluster.sh: line 103: fail: command not found 

### ISSUE THREAD

**Issue by schu** [gardener/landscape-setup#11]
https://github.com/gardener/landscape-setup/blob/master/components/kubify/wait_for_cluster.sh needs to source the common functions or be sourced in `components/kubify/deploy`.

Paging @Diaphteiros as the author :)

**Comment by msohn** [comment]
that's fixed in https://github.com/gardener/landscape-setup/commit/be2ce4e92c8f11cdee2a207aa234eecc849b7ec7 which is contained in
https://github.com/gardener/landscape-setup/releases/tag/0.1.0

**Comment by schu** [comment]
Ah, thanks @msohn I'm using landscape-setup-template which is still on an older version.

**Comment by msohn** [comment]
we are testing https://github.com/gardener/landscape-setup-template/pull/13 which is using this version.
At the moment we are stuck with some cert errors when trying to access the dashboard which we didn't see yesterday with an earlier version of this PR. @Diaphteiros is investigating this issue
