### ISSUE TITLE
Documentation issue on page "https://github.com/gardener/landscape-setup/blob/master/README.md"

### ISSUE THREAD

**Issue by freegroup** [gardener/landscape-setup#18]
broken markdown. Empty **a** tag with local anchor didn't work nor it is referenced in the document. In this case, it is waste and can be removed

```

## <a name="workaround"></a>Step 4.5: Workaround (Automated)

```
Some Markdown renderer adds a special annotation to links...

![bildschirmfoto 2018-07-26 um 11 58 59](https://user-images.githubusercontent.com/1155039/43255884-545d0da0-90cb-11e8-8348-b1fe9c19afe6.png)

---
Page: [https://github.com/gardener/landscape-setup/blob/master/README.md](https://github.com/gardener/landscape-setup/blob/master/README.md)
don't remove the link to the page. It's required for the processor

**Comment by plkokanov** [comment]
Also this link has to be fixed

**document**: https://github.com/gardener/landscape-setup/blob/master/README.md
**link**: https://github.com/gardener/gardener/blob/master/example/shoot-aws.yaml

**Comment by Diaphteiros** [comment]
Both fixes are now part of this pull request: https://github.com/gardener/landscape-setup/pull/17

**Comment by freegroup** [comment]
thanks
