### ISSUE TITLE
Gardener Hands-On Demo Setup

### ISSUE THREAD

**Issue by marwinski** [gardener/landscape-setup#21]
# Story

A a presenter I would like to quickly and easily set up a Gardener landscape (and remove it afterwards) that can be used hand-on by attendants.

# Motivation

A central landscape to be used by people who are not working for the organization might not be suitable for several reasons, such as security and privacy concerns. It should therefore be possible to set up a demo landscape with minimal effort prior to a hands-on demo and tear it down afterwards.

# Demo Flow

This is the proposed flow of the demo:

- the presenter sets up the Gardener in a clean and empty IaaS account
- the presenter create a project, e.g. "demo" and configures IaaS credentials
- the presenter adds attendees to the github organisation gardener-demo which is trused by Gardener and to the project
- attendees can play around, create clusters and access clusters
- after the session the presenter runs a script which removes all the shoots 
- presenter removes the Gardener by running the undeploy scripts (possibly the terraform destroy is sufficient
- presenter removes api access credetials and  checks that no reources are left in the IaaS account 

# Acceptance Criteria

- the whole procedure is documented  (including a security section which explains how to validate that the IaaS account is secure)
- (possible) automation of the set up delete procedures

**Comment by vlerenc** [comment]
Closing this one in favour of the new community installer https://github.com/gardener/garden-setup.
