### ISSUE TITLE
Gardener landscape installation on OpenStack

### ISSUE THREAD

**Issue by arnabnandy1706** [gardener/landscape-setup#32]
Hello,

Is it mandatory to use AWS Route53 for DNS if I am deploying for OpenStack?

Regards,
Arnab

**Comment by jiangytcn** [comment]
hi @arnabnandy1706 
I opened a PR to add support for openstack designate dns service.

https://github.com/gardener/kubify/pull/69

But having issue to make it work without comment out the route53 section, 
https://github.com/gardener/kubify/blob/6956bae14cac2a620a9ff7a3699db57e58791719/modules/dns/dns.tf#L76-L96

for designate setting, you can see this 
https://github.com/gardener/kubify/pull/69#issuecomment-474388135

And I just noticed landscape-setup is deprecated, need to switch other setup tool. would let you know if have any progress .

**Comment by vlerenc** [comment]
Closing this one in favour of the new community installer https://github.com/gardener/garden-setup.
