### ISSUE TITLE
Need to deploy Gardener on OpenStack

### ISSUE THREAD

**Issue by arnabnandy1706** [gardener/landscape-setup#33]
Hello Everyone,

I am facing some issue while trying to deploy the gardener landscape on OpenStack Enviroenment. I need to deploy the Gardener to showcase it to our clients.

Please help me with a dummy landscape_config.yaml and landscape_base.yaml for Openstack.

[Email: arnab.nandy1991@gmail.com]

Thanks in advance.

Regards,
Arnab

**Comment by arnabnandy1706** [comment]
Any suggestion please.

**Comment by Diaphteiros** [comment]
Sorry for the late reply. 

Please note that this setup is somewhat outdated by now and is going to be replaced by https://github.com/gardener/garden-setup 
I strongly recommend you use the new setup, as this one doesn't work with the current Gardener version. Unfortunately, the documentation for the new setup is still work in progress ... I'll check whether it is possible to publish a preliminary "how to", so the new setup becomes usable.

**Comment by vlerenc** [comment]
Closing this one in favour of the new community installer https://github.com/gardener/garden-setup.
